
server:
  port: 8075
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
spring:
  datasource:
    url: jdbc:h2:mem:appdb
    username: sa
  jpa:
    show-sql: true

